// lib/patchData.js
// All compiled TWID, TWAB, Dev Insight, and patch note weapon changes
// Keyed by weapon name for easy lookup. June 9, 2026 = Monument of Triumph (final update)

export const MOT_EXOTIC_CHANGES = {
  'The Jade Rabbit': {
    type: 'buff',
    catalyst: true,
    slot: 'Kinetic',
    weaponType: 'Scout Rifle',
    summary: 'Major rework — bigger mag, new perks, Micro Missile catalyst',
    changes: [
      { desc: 'Magazine increased from 10 to 15', changeType: 'buff' },
      { desc: 'Removed Zen Moment; added Shoot to Loot and Firefly as traits', changeType: 'buff' },
      { desc: 'Fate of All Fools: stacks cap increased to 15', changeType: 'buff' },
      { desc: 'Fate of All Fools: precision kills now add a stack (not just chaining)', changeType: 'buff' },
      { desc: 'Fate of All Fools: gaining a stack refills magazine and boosts stability', changeType: 'buff' },
      { desc: 'Fate of All Fools: stacks no longer fully cleared on reload', changeType: 'buff' },
      { desc: 'Firefly damage scales with active Fate of All Fools stacks', changeType: 'buff' },
      { desc: 'Catalyst: special reload consumes all stacks, fires a bonus Micro Missile round', changeType: 'catalyst' },
    ],
  },
  'Vex Mythoclast': {
    type: 'buff',
    catalyst: true,
    slot: 'Energy',
    weaponType: 'Fusion Rifle',
    summary: 'Significant PvE overhaul — ignitions, sustained-damage catalyst, visual HUD update',
    changes: [
      { desc: 'Timeless Mythoclast: full-auto mode now has a potent Rewind Rounds effect', changeType: 'buff' },
      { desc: 'Temporal Unlimiter: LFR precision kills now trigger an ignition', changeType: 'buff' },
      { desc: 'Temporal Unlimiter: magazine fully reloads after leaving LFR mode', changeType: 'buff' },
      { desc: 'HUD updated to show exact LFR shots remaining (visual only)', changeType: 'neutral' },
      { desc: 'Calculated Balance catalyst: now activates from sustained damage, not kills only', changeType: 'catalyst' },
      { desc: 'Calculated Balance catalyst: HUD buff indicator added', changeType: 'catalyst' },
    ],
  },
  'Touch of Malice': {
    type: 'buff',
    catalyst: true,
    slot: 'Kinetic',
    weaponType: 'Scout Rifle',
    summary: 'Final round damage up, faster special reload, Precision Instrument catalyst',
    changes: [
      { desc: 'Final round bonus damage increased by 10%', changeType: 'buff' },
      { desc: 'Special Reload speed now scales with reload stat', changeType: 'buff' },
      { desc: 'Catalyst: Rapid Hit replaced with Precision Instrument', changeType: 'catalyst' },
      { desc: 'Charged with Blight stacks now grant increased stability and reload speed', changeType: 'buff' },
    ],
  },
  'The Last Word': {
    type: 'buff',
    catalyst: false,
    slot: 'Kinetic',
    weaponType: 'Hand Cannon',
    summary: 'MnK-specific stability and aim assist improvements',
    changes: [
      { desc: 'MnK stability increased by 10', changeType: 'buff' },
      { desc: 'MnK hip-fire aim assist increased by 10', changeType: 'buff' },
    ],
  },
  'MIDA Multi-Tool': {
    type: 'buff',
    catalyst: true,
    slot: 'Kinetic',
    weaponType: 'Scout Rifle',
    summary: 'PvE kill requirements significantly reduced',
    changes: [
      { desc: 'PvE kill requirement per modification: 10→7 (15→10 with Macro-Tool)', changeType: 'buff' },
      { desc: 'Total kills to unlock all modifications: 40(60)→27(40)', changeType: 'buff' },
      { desc: 'Catalyst improved radar resolution activates sooner', changeType: 'catalyst' },
    ],
  },
  'Tarrabah': {
    type: 'buff',
    catalyst: false,
    slot: 'Energy',
    weaponType: 'Submachine Gun',
    summary: 'Ravenous Beast stacks survive death in PvE',
    changes: [
      { desc: 'Ravenous Beast stacks no longer lost on death in PvE', changeType: 'buff' },
      { desc: 'Stack drain rate slowed significantly in PvE', changeType: 'buff' },
    ],
  },
  'Anarchy': {
    type: 'rework',
    catalyst: true,
    slot: 'Power',
    weaponType: 'Grenade Launcher',
    summary: 'Full rework — arc wire chains to multiple targets, new Voltaic Snare catalyst',
    changes: [
      { desc: 'Arc wire tethers now chain to additional nearby targets', changeType: 'buff' },
      { desc: 'Tether damage scales with number of chained targets', changeType: 'buff' },
      { desc: 'Catalyst: Voltaic Snare — tethers root Unstoppable Champions', changeType: 'catalyst' },
    ],
  },
  'Divinity': {
    type: 'nerf',
    catalyst: false,
    slot: 'Energy',
    weaponType: 'Trace Rifle',
    summary: 'Cage build-up slower, weaken debuff reduced',
    changes: [
      { desc: 'Precision cage build-up time increased by 75% (PvP unchanged)', changeType: 'nerf' },
      { desc: 'Weaken effect on caged target reduced from 15% to 12%', changeType: 'nerf' },
    ],
  },
  'Winterbite': {
    type: 'buff',
    catalyst: false,
    slot: 'Power',
    weaponType: 'Glaive',
    summary: 'Faster projectiles, better tracking, longer freeze',
    changes: [
      { desc: 'Projectile speed increased', changeType: 'buff' },
      { desc: 'Icy Grapple freeze duration increased by 20%', changeType: 'buff' },
      { desc: 'Intrinsic tracking improved', changeType: 'buff' },
    ],
  },
  'Edge of Action': {
    type: 'buff',
    catalyst: false,
    slot: 'Power',
    weaponType: 'Glaive',
    summary: 'Titan Barricade synergy massively improved',
    changes: [
      { desc: 'Titan Barricade: Ward of Dawn recharge rate doubled while active', changeType: 'buff' },
      { desc: 'Barrier now grants overshield on entry', changeType: 'buff' },
    ],
  },
  'Edge of Concurrence': {
    type: 'buff',
    catalyst: false,
    slot: 'Power',
    weaponType: 'Glaive',
    summary: 'More arc chains, higher chain damage',
    changes: [
      { desc: 'Hunter Dodge: chain lightning arcs increased from 3 to 5', changeType: 'buff' },
      { desc: 'Arc chain damage increased by 15%', changeType: 'buff' },
    ],
  },
  'Edge of Intent': {
    type: 'buff',
    catalyst: false,
    slot: 'Power',
    weaponType: 'Glaive',
    summary: 'Warlock rift healing upgraded',
    changes: [
      { desc: 'Warlock Rift: healing rift now also applies Restoration x2', changeType: 'buff' },
      { desc: 'Well of Radiance: lingering healing duration increased', changeType: 'buff' },
    ],
  },
  'Hierarchy of Needs': {
    type: 'buff',
    catalyst: false,
    slot: 'Power',
    weaponType: 'Bow',
    summary: 'Guidance Ring stacks to 3x, Seraph Bolts stronger',
    changes: [
      { desc: 'Guidance Ring now stacks up to 3 times', changeType: 'buff' },
      { desc: 'Seraph Bolt damage increased by 20%', changeType: 'buff' },
      { desc: 'Bolts now track aggressively in PvE', changeType: 'buff' },
    ],
  },
  'Sunshot': {
    type: 'buff',
    catalyst: true,
    slot: 'Energy',
    weaponType: 'Hand Cannon',
    summary: 'Sun Blast radius up, chained explosions, new Solar pools',
    changes: [
      { desc: 'Sun Blast explosion radius increased by 25% in PvE', changeType: 'buff' },
      { desc: 'Chained explosions now create Solar energy pools', changeType: 'buff' },
      { desc: 'Catalyst: Ignitions chain to 1 additional target', changeType: 'catalyst' },
    ],
  },
  'Graviton Lance': {
    type: 'buff',
    catalyst: true,
    slot: 'Energy',
    weaponType: 'Pulse Rifle',
    summary: 'Cosmology projectile damage up, suppression via catalyst',
    changes: [
      { desc: 'Cosmology void projectile damage increased by 15%', changeType: 'buff' },
      { desc: 'Black Hole damage bonus increased', changeType: 'buff' },
      { desc: 'Catalyst: Cosmology projectiles now suppress targets', changeType: 'catalyst' },
    ],
  },
  'Outbreak Perfected': {
    type: 'buff',
    catalyst: true,
    slot: 'Kinetic',
    weaponType: 'Pulse Rifle',
    summary: 'SIVA nanite damage up, smarter targeting, Orb generation',
    changes: [
      { desc: 'SIVA nanite swarm damage per tick increased by 20%', changeType: 'buff' },
      { desc: 'Nanites now prioritize mini-bosses', changeType: 'buff' },
      { desc: 'Catalyst: nanite kills generate Orbs of Power', changeType: 'catalyst' },
    ],
  },
  'Arbalest': {
    type: 'nerf',
    catalyst: false,
    slot: 'Kinetic',
    weaponType: 'Linear Fusion Rifle',
    summary: 'Shield-break damage and Disruption Break duration reduced',
    changes: [
      { desc: 'Shield-break bonus damage reduced from 50% to 40%', changeType: 'nerf' },
      { desc: 'Disruption Break duration reduced from 7s to 5s', changeType: 'nerf' },
    ],
  },
  'Wardcliff Coil': {
    type: 'rework',
    catalyst: true,
    slot: 'Power',
    weaponType: 'Rocket Launcher',
    summary: 'Bipod removed, volley tightened, Warlock catalyst synergy',
    changes: [
      { desc: 'Bipod perk removed; replaced with Overflow', changeType: 'rework' },
      { desc: 'Volley spread pattern tightened for better target grouping', changeType: 'buff' },
      { desc: 'Catalyst: Mad Scientist grants auto-reload from Warlock healing rift', changeType: 'catalyst' },
    ],
  },
  'The Lament': {
    type: 'buff',
    catalyst: false,
    slot: 'Power',
    weaponType: 'Sword',
    summary: 'Better block DR, higher Banshee\'s Wail damage, easier revving',
    changes: [
      { desc: 'Revved sword block: damage reduction increased from 60% to 75%', changeType: 'buff' },
      { desc: 'Banshee\'s Wail damage per hit increased by 15%', changeType: 'buff' },
      { desc: 'Ease of revving improved (shorter input window required)', changeType: 'buff' },
    ],
  },
  'Truth': {
    type: 'buff',
    catalyst: true,
    slot: 'Power',
    weaponType: 'Rocket Launcher',
    summary: 'Better tracking, cluster bomb damage up, Incendiary Pool catalyst',
    changes: [
      { desc: 'Prototype Trueseeker tracking aggressiveness increased', changeType: 'buff' },
      { desc: 'Cluster Bomb damage increased by 10%', changeType: 'buff' },
      { desc: 'Catalyst: rockets leave an Incendiary Pool on detonation', changeType: 'catalyst' },
    ],
  },
  'Thunderlord': {
    type: 'buff',
    catalyst: true,
    slot: 'Power',
    weaponType: 'Machine Gun',
    summary: 'Arc Conductor damage up, larger Feeding Frenzy stack cap, ammo on proc',
    changes: [
      { desc: 'Arc Conductor damage bonus increased by 20%', changeType: 'buff' },
      { desc: 'Feeding Frenzy stack cap increased from 5 to 7', changeType: 'buff' },
      { desc: 'Catalyst: kills during Arc Conductor generate 2 ammo per kill', changeType: 'catalyst' },
    ],
  },
  'Whirling Ovation': {
    type: 'rework',
    catalyst: false,
    slot: 'Energy',
    weaponType: 'Auto Rifle',
    summary: 'Dance Routine persists through swaps, Ovation damage up, new perk',
    changes: [
      { desc: 'Dance Routine now persists through weapon swaps for 3 seconds', changeType: 'buff' },
      { desc: 'Ovation proc damage increased by 25%', changeType: 'buff' },
      { desc: 'Destabilizing Rounds added to trait pool', changeType: 'buff' },
    ],
  },
  'Prometheus Lens': {
    type: 'buff',
    catalyst: false,
    slot: 'Energy',
    weaponType: 'Trace Rifle',
    summary: 'Faster damage ticks, wider Flame Refraction, Solar Strand synergy',
    changes: [
      { desc: 'Prismatic Inferno damage tick rate increased', changeType: 'buff' },
      { desc: 'Flame Refraction width increased by 30%', changeType: 'buff' },
      { desc: 'Now generates Warmth stacks in Solar Strand builds', changeType: 'buff' },
    ],
  },
  'Centrifuse': {
    type: 'buff',
    catalyst: true,
    slot: 'Energy',
    weaponType: 'Auto Rifle',
    summary: 'Faster charge, bigger discharge radius, Amplified on catalyst',
    changes: [
      { desc: 'Bullet Attractor charge rate increased by 25%', changeType: 'buff' },
      { desc: 'Discharge radius increased by 20%', changeType: 'buff' },
      { desc: 'Catalyst: charged discharge now applies Amplified to player', changeType: 'catalyst' },
    ],
  },
  "Slayer's Fang": {
    type: 'buff',
    catalyst: false,
    slot: 'Energy',
    weaponType: 'Submachine Gun',
    summary: 'Better tracking, higher stack cap, more bonus damage',
    changes: [
      { desc: 'Slayer Bolt tracking improved significantly', changeType: 'buff' },
      { desc: 'Max stacks increased from 5 to 7', changeType: 'buff' },
      { desc: 'Bonus damage at max stacks increased by 10%', changeType: 'buff' },
    ],
  },
  'Xenophage': {
    type: 'rework',
    catalyst: true,
    slot: 'Power',
    weaponType: 'Machine Gun',
    summary: 'Full rework — Pyromania out, Incandescent in, Orb synergy',
    changes: [
      { desc: 'Pyromania removed; replaced with Incandescent', changeType: 'rework' },
      { desc: 'Explosive Light now works with Orbs of Power', changeType: 'buff' },
      { desc: 'Catalyst: Incandescent chains to 2 additional targets; ignitions trigger at full stack', changeType: 'catalyst' },
    ],
  },
}

export const ARCHETYPE_CHANGES = {
  'Auto Rifle': { change: 'buff', notes: 'Baseline stability +5 across all archetypes; Aggressive Frames receive +8% PvE damage' },
  'Pulse Rifle': { change: 'neutral', notes: 'No archetype-wide changes in MoT; exotic-level tweaks only (Graviton Lance, Outbreak Perfected)' },
  'Hand Cannon': { change: 'buff', notes: 'Lightweight Frames: aim assist cone +3%; 120 RPM: range falloff start +2m' },
  'Scout Rifle': { change: 'buff', notes: 'Aggressive Frames: damage vs. shielded enemies +8%' },
  'Submachine Gun': { change: 'neutral', notes: 'No archetype changes; Closing Time perk nerfed separately in 8.2.5.1' },
  'Sidearm': { change: 'neutral', notes: 'No archetype changes in MoT' },
  'Shotgun': { change: 'buff', notes: 'Precision Frames: pellet spread -5%; slug base damage +7%' },
  'Fusion Rifle': { change: 'buff', notes: 'Rapid-Fire Frames: bolt count 7→8; charge time -5ms' },
  'Sniper Rifle': { change: 'buff', notes: 'Aggressive Frames: flinch resistance +15%; Adaptive: bonus damage to orange bars +10%' },
  'Grenade Launcher': { change: 'buff', notes: 'Wave-Frame: wave height +30%; Adaptive: blast radius +10%' },
  'Rocket Launcher': { change: 'buff', notes: 'High-Impact Frames: PvE damage +10%; Precision Frames: tracking updated' },
  'Linear Fusion Rifle': { change: 'buff', notes: 'Precision Frames: crit damage +8%; Aggressive: ammo reserves +5' },
  'Sword': { change: 'buff', notes: 'Caster Frames: projectile speed +20%; Adaptive: heavy attack damage +12%' },
  'Glaive': { change: 'buff', notes: 'Shield duration +1s; projectile damage +10% across all frames' },
  'Machine Gun': { change: 'buff', notes: 'High-Impact: damage vs. Elite enemies +12%; Adaptive: mag size +5' },
  'Bow': { change: 'buff', notes: 'Precision Frames: draw time -15ms; Lightweight: arrow speed +10%' },
  'Trace Rifle': { change: 'buff', notes: 'Damage vs. Barrier Champions +15%; sustained DPS increased across all frames' },
}

export const PATCH_FEED = [
  {
    date: 'May 29, 2026',
    patch: 'Pre-MoT Dev Insight',
    source: 'devinsight',
    url: 'https://www.bungie.net/7/en/News/Article/dev_insights_weapons_artifacts_focusing_preview',
    title: 'Dev Insights: Weapons, Artifacts & Focusing Preview',
    summary: 'Bungie sandbox team published full details on 27 Exotic weapon changes coming June 9. Weapon Tier Upgrading (Tiers 1-5) introduced for crafted weapons. Anti-Champion reworked — now tied to subclass verbs + universal armor mods instead of seasonal weapon mods.',
    weaponChanges: [
      { name: 'The Jade Rabbit', type: 'buff' }, { name: 'Vex Mythoclast', type: 'buff' },
      { name: 'Anarchy', type: 'rework' }, { name: 'Divinity', type: 'nerf' },
      { name: 'Wardcliff Coil', type: 'rework' }, { name: 'Xenophage', type: 'rework' },
      { name: 'Sunshot', type: 'buff' }, { name: 'Graviton Lance', type: 'buff' },
      { name: 'Arbalest', type: 'nerf' }, { name: 'Thunderlord', type: 'buff' },
      { name: 'The Lament', type: 'buff' }, { name: 'Truth', type: 'buff' },
    ],
  },
  {
    date: 'May 21, 2026',
    patch: 'Monument of Triumph Announcement',
    source: 'twid',
    url: 'https://www.bungie.net/7/en/News/article/d2_may_21_2026',
    title: 'Every End is a New Beginning — Final Update Announcement',
    summary: 'Bungie confirmed June 9 as the final live-service update. All raid/dungeon weapons brought to full Tier parity with new perks and set bonuses. Crafted weapons get Tier 1-5 upgrade paths. Destination weapons refreshed. New Exotic Hand Cannon in Rewards Pass. Exotic weapon tuning pass + 25 new catalysts confirmed.',
    weaponChanges: [
      { name: 'All Raid & Dungeon Weapons', type: 'rework' },
      { name: 'All Destination Weapons', type: 'buff' },
      { name: 'New Exotic Hand Cannon', type: 'buff' },
      { name: '25 New Exotic Catalysts', type: 'buff' },
    ],
  },
  {
    date: 'March 14, 2025',
    patch: '8.2.5.1',
    source: 'twid',
    url: 'https://www.bungie.net',
    title: 'Episode Heresy: Closing Time Nerf + Dance Machines Update',
    summary: 'The Closing Time perk nerfed — stat buff window tightened, especially on Special ammo weapons in Crucible. Dead Man\'s Tale and The Last Word re-enabled with Radiant Dance Machines but limited to non-range buffs only.',
    weaponChanges: [
      { name: "Zealot's Reward", type: 'nerf' },
      { name: "Dead Man's Tale", type: 'nerf' },
      { name: 'The Last Word', type: 'nerf' },
    ],
  },
  {
    date: 'June 4, 2024',
    patch: '8.0.0.1',
    source: 'patchnotes',
    url: 'https://www.bungie.net',
    title: 'The Final Shape Launch — Major Sandbox Overhaul',
    summary: 'Pulse Rifles +20% PvE damage, Fusion Rifles +7%, Sniper Rifles +7%. Divinity cage slowed 75%. Necrochasm buffed. Osteo Striga nerfed. Strand Titan nerfed. New Frost Armor keyword for Stasis builds. Well of Radiance nerfed.',
    weaponChanges: [
      { name: 'Pulse Rifles', type: 'buff' }, { name: 'Fusion Rifles', type: 'buff' },
      { name: 'Sniper Rifles', type: 'buff' }, { name: 'Divinity', type: 'nerf' },
      { name: 'Necrochasm', type: 'buff' }, { name: 'Osteo Striga', type: 'nerf' },
    ],
  },
  {
    date: 'March 5, 2024',
    patch: '7.3.5',
    source: 'patchnotes',
    url: 'https://www.bungie.net',
    title: 'Hotfix 7.3.5 — Mid-Season Weapon Tuning',
    summary: 'Heavy Burst Hand Cannons nerfed across the board. Bow draw time reduced on Precision Frames. Auto Rifles stability increased. Lightweight Scout Rifles improved aim assist. Aggressive Sniper Rifles gained flinch resistance.',
    weaponChanges: [
      { name: 'Heavy Burst Hand Cannons', type: 'nerf' }, { name: 'Bows', type: 'buff' },
      { name: 'Auto Rifles', type: 'buff' }, { name: 'Lightweight Scout Rifles', type: 'buff' },
      { name: 'Sniper Rifles', type: 'buff' },
    ],
  },
  {
    date: 'October 2022',
    patch: 'Season of Plunder Mid-Season',
    source: 'twid',
    url: 'https://www.bungie.net',
    title: 'Season of Plunder: Sandbox Changes + Rangefinder Nerf',
    summary: 'Auto Rifles and Trace Rifles got sizeable stability bumps. Adaptive Pulse Rifles and Precision Auto Rifles got crit damage increases. Pulse Rifle effective range reduced at low-mid stat values. Rangefinder nerfed. Lord of Wolves sniper flinch rework.',
    weaponChanges: [
      { name: 'Auto Rifles', type: 'buff' }, { name: 'Trace Rifles', type: 'buff' },
      { name: 'Adaptive Pulse Rifles', type: 'buff' }, { name: 'Pulse Rifles', type: 'nerf' },
      { name: 'Lord of Wolves', type: 'rework' },
    ],
  },
]

export const TIER_LIST = {
  S: [
    { name: 'Anarchy (reworked)', rarity: 'Exotic', type: 'Grenade Launcher', reason: 'Multi-target tether chains + Unstoppable catalyst = undisputed king' },
    { name: 'Thunderlord', rarity: 'Exotic', type: 'Machine Gun', reason: 'Arc Conductor buff + ammo generation makes this self-sustaining' },
    { name: 'The Lament', rarity: 'Exotic', type: 'Sword', reason: '75% block DR + Banshee\'s Wail buff = best DPS sword in the game' },
    { name: 'Vex Mythoclast', rarity: 'Exotic', type: 'Fusion Rifle', reason: 'Ignitions from LFR mode + Rewind Rounds finally makes PvE viable' },
    { name: 'Sunshot', rarity: 'Exotic', type: 'Hand Cannon', reason: 'Solar pool generation + chain ignitions = add-clear supremacy' },
    { name: 'Outbreak Perfected', rarity: 'Exotic', type: 'Pulse Rifle', reason: 'Nanite damage up 20% + Orb generation = best primary for endgame' },
    { name: 'Xenophage (reworked)', rarity: 'Exotic', type: 'Machine Gun', reason: 'Incandescent rework + Orb synergy makes it the Incandescent MG' },
  ],
  A: [
    { name: 'The Jade Rabbit', rarity: 'Exotic', type: 'Scout Rifle', reason: 'Full rework makes this genuinely competitive in PvE for the first time' },
    { name: 'Truth', rarity: 'Exotic', type: 'Rocket Launcher', reason: 'Better tracking + Incendiary Pool catalyst = reliable endgame rocket' },
    { name: 'Graviton Lance', rarity: 'Exotic', type: 'Pulse Rifle', reason: 'Suppressing Cosmology projectiles are incredible in champion content' },
    { name: 'Wardcliff Coil (reworked)', rarity: 'Exotic', type: 'Rocket Launcher', reason: 'Tighter volley pattern finally makes it hit consistently' },
    { name: 'Touch of Malice', rarity: 'Exotic', type: 'Scout Rifle', reason: 'Final round damage buff + Precision Instrument catalyst = boss DPS option' },
    { name: 'High-Impact Rocket Launchers', rarity: 'Legendary', type: 'Rocket Launcher', reason: '+10% PvE damage is a straight upgrade for the archetype' },
    { name: 'Adaptive Linear Fusion Rifles', rarity: 'Legendary', type: 'Linear Fusion Rifle', reason: 'Crit damage buff + reserve increase makes these top DPS' },
  ],
  B: [
    { name: 'Hierarchy of Needs', rarity: 'Exotic', type: 'Bow', reason: '3x Guidance Ring stacking + 20% bolt damage is good but situational' },
    { name: 'Winterbite', rarity: 'Exotic', type: 'Glaive', reason: 'Freeze duration and tracking improved; still niche' },
    { name: 'Prometheus Lens', rarity: 'Exotic', type: 'Trace Rifle', reason: 'Wider Refraction + faster ticks is solid; competes with other Trace Rifles' },
    { name: 'Tarrabah', rarity: 'Exotic', type: 'Submachine Gun', reason: 'Stack persistence in PvE finally makes this farmable' },
    { name: "Slayer's Fang", rarity: 'Exotic', type: 'Submachine Gun', reason: 'Tracking + stack cap buffs bring it to a reliable pick' },
    { name: 'Centrifuse', rarity: 'Exotic', type: 'Auto Rifle', reason: 'Amplified on discharge catalyst is strong; charge rate makes it usable' },
    { name: 'High-Impact Machine Guns', rarity: 'Legendary', type: 'Machine Gun', reason: '+12% elite damage means these rival the exotic MGs in most content' },
  ],
  C: [
    { name: 'Edge of Action', rarity: 'Exotic', type: 'Glaive', reason: 'WoD recharge buff is nice but Titan exotic slots are very competitive' },
    { name: 'Edge of Concurrence', rarity: 'Exotic', type: 'Glaive', reason: '5 arc chains is fun but damage still trails other exotic options' },
    { name: 'Edge of Intent', rarity: 'Exotic', type: 'Glaive', reason: 'Restoration x2 is strong; competes with Phoenix Protocol and Lunafaction' },
    { name: 'MIDA Multi-Tool', rarity: 'Exotic', type: 'Scout Rifle', reason: 'Easier PvE quest is welcome; weapon itself unchanged in sandbox terms' },
    { name: 'Whirling Ovation (reworked)', rarity: 'Exotic', type: 'Auto Rifle', reason: 'Rework is interesting but Auto Rifle exotic slot is crowded' },
    { name: '120 RPM Hand Cannons', rarity: 'Legendary', type: 'Hand Cannon', reason: 'Range falloff buff helps; still not the primary meta archetype' },
  ],
  D: [
    { name: 'Arbalest', rarity: 'Exotic', type: 'Linear Fusion Rifle', reason: 'Both nerfs hit its core identity; other anti-shield options now better' },
    { name: 'Divinity', rarity: 'Exotic', type: 'Trace Rifle', reason: 'Second consecutive nerf; cage is too slow to justify the exotic slot in most content' },
    { name: 'The Last Word', rarity: 'Exotic', type: 'Hand Cannon', reason: 'MnK buffs are too small; still a PvP-only niche pick' },
  ],
}
